### ISSUE TITLE
amd64 images

### ISSUE THREAD

**Issue by rgl** [cirruslabs/vetu#34]
Will amd64 images be available too?

Since there is an amd64 `vetu` binary, I've assumed, there were images too, but, when trying it on a amd64 machine, it fails as:

```console
$ vetu run ubuntu
2023/12/14 13:01:33 this VM is built to run on "arm64", but you're running "amd64"
```

Probably, `vetu clone` should default to downloading images for the current architecture, and fail at the step immediately when it does not exist.

**Comment by edigaryev** [comment]
Unfortunately, at the moment we only provide `arm64` images [compatible with Tart](https://tart.run/quick-start/#vm-images).

But you can always build your own images pretty easily from {Ubuntu, Debian, Fedora, etc.} cloud images.

See https://github.com/cirruslabs/linux-image-templates for an example on how to do that (this is a repository of CI tasks that builds the Tart `arm64` images).

**Comment by rgl** [comment]
Not sure how far supporting amd64 is from landing there. In the meantime maybe more explicitly mention that only arm64 is supported at the moment?

I'm aware of the repos you've mentioned. They use packer with the tart plug-in, is there an vetu equivalent? If not, do you have an example of creating an image from scratch? Are they the same as in tart, but using the vetu cli in amd64?

**Comment by fkorotkov** [comment]
You can try `ghcr.io/cirruslabs/ubuntu-runner-amd64:22.04` image now.
