### ISSUE TITLE
Adhere to XDG Base Directory Specification

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/vetu#47]
I'd like `vetu` to adhere to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), by e.g. placing downloaded images into `$XDG_CACHE_HOME` instead of cluttering home directory.

**Comment by edigaryev** [comment]
Please see https://github.com/cirruslabs/tart/issues/765#issuecomment-2017534250.

It's pretty much the same in Vetu as of https://github.com/cirruslabs/vetu/pull/46.

**Comment by torarnv** [comment]
macOS is not a [Freedesktop](https://www.freedesktop.org/wiki/) platform, so I don't think it makes sense for Vetu to pick up the various `XDG_` environment variables.

**Comment by fkorotkov** [comment]
Agreed with both points. Closing since we are not planning to support it.
